language: node_js
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
branches:
    # We need to whitelist the branches which we want to have "push" automation.
    # Pull request automation is not constrained to this set of branches.
    only:
        - master
script: npm test
